spring.application.name=CadastroDeNinjas

# CONFIGURAÇÃO DO H2 DB
spring.datasource.url=${DATABASE_URL}
spring.datasource.driver=org.h2.Driver
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}

# CONFIGURAÇÃO DO JPA // HIBERNATES
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

